baseurl = "https://eclipse-pass.org/"
DefaultContentLanguage = "en"
title = "Eclipse Public Access Submission System (PASS)"
theme = "hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = []
enableRobotsTXT = true
pluralizeListTitles = false

[Params]
#  google_tag_manager = "GTM-5WLCZXC"
  description = "Eclipse PASS is a platform to assist researchers in complying with the access policies of their funders and institutions."
  seo_title_suffix = " | Eclipse Public Access Submission System (PASS)"
  keywords = ["open access", "pass", "public access submission system"]
  news_count = 0
#  gcse = "011805775785170369411:p3ec0igo0qq"
  header_wrapper_class = "header-wrapper header-default-bg-img featured-jumbotron-bottom-shape"
#  call_for_action_text = "Download"
#  call_for_action_url = "//eclipse.org/download/"
#  call_for_action_icon = "fa-download"
# sidebar_layout = "default"
# featured_content_publish_target = "eclipse_org"
#  js = ""
#  styles = ""
#  logo = ""
#  favicon = ""
#  share_img = ""
#  logo_width = ""
#  header_left_classes = ""
#  main_menu_wrapper_classes = ""
#  projects_working_group = ""

  
[taxonomies]
  category = "categories"
  tag = "tags"
  membership_level = "membership_levels"
  participation_level = "participation_levels"

[Author]
#  name = "Christopher Guindon"
  website = "https://eclipse-pass.org/"
#  email = "webdev@eclipse-foundation.org"
#  facebook = "eclipse.org"
#  twitter = "ECDTools"
#  youtube = "EclipseFdn"
#  googleplus = "+Eclipse"
#  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

